version: 2.1

jobs:
  push_To_DockerHub:
    docker:
      - image: cimg/base:stable  # CircleCI's base image with Docker support
    steps:
      - checkout

      - setup_remote_docker  # Use default Docker version (currently Docker 24.0.6)

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_API_KEY" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image with version and latest tags
          command: |
            docker build -t $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG .
            docker tag $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG \
                       $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:latest

      - run:
          name: Push Docker images (version & latest)
          command: |
            docker push $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG
            docker push $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:latest
  push_To_Github:
    docker:
      - image: cimg/base:stable  # CircleCI's base image with Docker support
    steps:
      - checkout

      - setup_remote_docker  # Use default Docker version (currently Docker 24.0.6)

      - run:
          name: Login to GitHub Container Registry
          command: |
            echo "$GITHUB_TOKEN" | docker login $GITHUB_REGISTRY -u $GITHUB_USERNAME --password-stdin

      - run:
          name: Build Docker image with version and latest tags
          command: |
            docker build -t $GITHUB_REGISTRY/$GITHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG .
            docker tag $GITHUB_REGISTRY/$GITHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG \
            $GITHUB_REGISTRY/$GITHUB_USERNAME/$DOCKER_IMAGE:latest

      - run:
          name: Push Docker images (version & latest)
          command: |
            docker push $GITHUB_REGISTRY/$GITHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG
            docker push $GITHUB_REGISTRY/$GITHUB_USERNAME/$DOCKER_IMAGE:latest

workflows:
  version: 2
  deploy_docker:
    jobs:
      - push_To_DockerHub:
          filters:
            branches:
              only:
                - main
      - push_To_Github:
          filters:
            branches:
              only:
                - main
