version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:stable  # Use CircleCI base image that supports Docker
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.18  # Or latest supported version

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_API_KEY" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image with version and latest tags
          command: |
            docker build -t $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG .
            docker tag $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG \
                       $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:latest

      - run:
          name: Push Docker images (version & latest)
          command: |
            docker push $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:$DOCKER_VERSION_TAG
            docker push $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/$DOCKER_IMAGE:latest

workflows:
  version: 2
  deploy_docker:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - main
